apiVersion: v1
kind: Service
metadata:
  name: go-service
  namespace: demo-ops
spec:
  selector:
    app: go-app
  ports:
    - protocol: TCP 
      port: 80
      targetPort: 8080
  type: LoadBalancer

